### ISSUE TITLE
Npm module not independent

### ISSUE THREAD

**Issue by milanpro** [cginternals/webgl-operate#139]
After installing webgl-operate via npm to use it in my react app, i also had to install rxjs and gl-matrix. Without them i got compile errors. Maybe add them as dependencies to the package?

**Comment by cgcostume** [comment]
Thanks for reporting. This is hard to do, since we setup rxjs as a peerDependencies which is some how not working, aka not supported well by npm. We do not want to bundle rxjs. Instead, your react app needs to (at least for now) install this manually. Please let us know if you have a better/alternative solution for this. 

Adding them directly as a dependency results rxjs to be in the bundle. If you then deploy an application or library on top of webgl-operate, that uses rxjs as well, then you end up having two different rxjs implementations at run-time.

For gl-matrix though, this should work. Except that quat is not exported (just found this... will be added asap).

**Comment by cgcostume** [comment]
since gl-matrix is now included, and rxjs peer-dependency-use is explicitly handled via webpack, all the above issues should be resolved.
