### ISSUE TITLE
Rotation-Problems with Edge-Browser

### ISSUE THREAD

**Issue by Jens23** [cginternals/webgl-operate#158]
If you try to rotate the cornell box in the Microsoft edge browser, you only drag the renderview of the
cornell box.
![bug operate edge rotieren](https://user-images.githubusercontent.com/46416287/50734544-fd159380-11a0-11e9-8e73-8ade0035918b.png)

**Comment by cgcostume** [comment]
Thanks for the report.I cannot reproduce this behavior though. This is what I see:

![ezgif-2-b15c8a46fd34](https://user-images.githubusercontent.com/3909980/53819824-f91cac80-3f6a-11e9-83f5-6e9beb4a0eaa.gif)

Can you please check the console output and provide further information.

**Comment by Jens23** [comment]
![console](https://user-images.githubusercontent.com/46416287/53915957-424f2800-4061-11e9-9d05-8f3034591ec1.png)
The problem appears after rotating the box several times, often already after the second or third time. 
But nothing is written into the console. 
In the console, the scaling is the only mentioned thing, and that happens directly when the page is called.

**Comment by cgcostume** [comment]
Thanks, i can reproduce now. The issue can be "fixed" doing the following:
```
document.getElementsByTagName('canvas')[0].ondragstart = function() { return false; }
```

But i'm not sure if this is an issue of edge, webgl, or webgl-operate. I will investigate further and provide a fix asap.

**Comment by cgcostume** [comment]
The drag behavior in Edge seems to be intentional/desired. Compared to other browsers, where you can drag and drop arbitrary website content, Edge creates a screenshot-like representation of the dragged content (including any canvas context) which is then rendered by windows (not Edge) on top of all other desktop elements. You can test this, e.g., on the webgl-operate.org website by pressing CTRL+A and start drag ... Somehow the detection of the user's intent - drag vs. common mouse interaction in canvas - is inconvenient for common canvas uses.

As fix I will prevent the drag start event in the `MouseEventProvider` of webgl-operate by default. Thus, if some one uses mouse events, this behavior will not occur. That also means, that the Edge behavior will not be 'fixed' when using a webgl-operate canvas with other means of interaction or custom event provider (except the mouse event provider). Three.js seems to have a similar behavior, there, the drag behavior is only prevented when camera navigation is present.
