### ISSUE TITLE
Masquerade input not working for examples

### ISSUE THREAD

**Issue by anne-gropler** [cginternals/webgl-operate#268]
I am using the Masquerade input (e.g., `?msqrd_h=1M+-1n`, which is my current Safari) to see if things work on different browser+webgl combinations.

However, `contextmasquerade.ts:fromGET` does not seem to get my input:
```
   static fromGET(): ContextMasquerade | undefined {
        const msqrdHash = GETparameter('msqrd_h');
        console.log('?msqrd_h=1M+-1n turned out to be:', msqrdHash)  // <----------- msqrdHash is undefined!
        if (msqrdHash !== undefined) {
            return ContextMasquerade.fromHash(msqrdHash);
        }
        const msqrdPreset = GETparameter('msqrd_p');
        if (msqrdPreset !== undefined) {
            return ContextMasquerade.fromPreset(msqrdPreset);
        }
        return undefined;
    }
```

It works well on `webgl-operate.org`, but not on `webgl-operate.org/examples`. However, I find it quite important to check how the examples work with different webgl version and different extensions.

**Comment by bakoe** [comment]
I’ve stumbled across the same problem while investigating the Safari support of webgl-operate (see #269) – thanks for reporting, @anne-gropler! 

It seems like the bug is due to https://webgl-operate.org/examples/ including the actual examples in an iframe, leading to the `window.location.search` variable used in the `GETparameter()` auxiliary function being empty (`""`) in that case: 

https://github.com/cginternals/webgl-operate/blob/10bdd97a711ac2f0a356ddf7b0745217e6a278f9/source/auxiliaries.ts#L309-L320

I’ve submitted a PR that seemingly fixes that problem by introducing an additional, subsequent check for `window.top.location.search` in the `GETparameter()` auxiliary function: #270.

**Comment by scheibel** [comment]
Thanks for the analysis. I want to confirm this behavior, as the examples are embedded using iframes.
What is a caveat in this case, I want to point out as a perk and propose a workaround right away: open the location of the iframe as own instance, where you can manipulate the context masquerade as expected.
As both use cases seem reasonable, we should integrate #270.

**Comment by cgcostume** [comment]
Since the PR of @bakoe was integrated by @scheibel I assume the issue to be resolved (please re-open if not).
