### ISSUE TITLE
Does it support fallback Canvas API if WebGL isn't available?

### ISSUE THREAD

**Issue by nvcken** [cginternals/webgl-operate#95]
In case old mobile browsers without WebGL supported

**Comment by cgcostume** [comment]
As far as i understand the question, no it does not, it is an hardware accelerated approach only and relies on at least an webgl context. 

Old mobile browsers might support a Mesa based software renderer though, so if most basic WebGL is used, there should be no problems for devices starting from 2012 ... We have several demos and products deployed based on webgl-operate and they usually work on old devices as well, such as my old Samsung Galaxy Alpha (Chrome on Android 4 or 5).

**Comment by nvcken** [comment]
thanks, may I ask any reason why not use ThreeJS

**Comment by cgcostume** [comment]
Feel free to use ThreeJS - we use it a lot as well! It's one of the best engines available!

short version: Hardware accelerated rendering cannot be abstracted/simplified while maintaining the flexibility of the underlying graphics API at the same time. WebGL operate makes working with WebGL easier, not rendering itself.

background: The difference between common rendering engines and webgl-operate is mainly that webgl-operate provides a use case agnostic WebGL framework: Path-tracing, Ray Marching, Ray Tracing, Multi-frame Sampling, Forward Rendering, Deferred Rendering, Image Processing, and many more ... nothing is aggravated/excluded. Thus, it is not an actual rendering engine since this would require a focus on a specific kind of rendering. In most industry applications we face, rendering and interaction is highly use case specific and we never found a single engine (desktop, mobile, or web) to provide meaning full help/support. Instead, using rendering engines always resulted in lots of overhead, e.g., conforming to the existing mechanics and architecture instead of focusing on the best possible rendering and interaction approach itself. This is why we created webgl-operate (and gloperate). 

If you have a content driven project that relies on common rendering techniques, you probably should not use webgl-operate.

**Comment by cgcostume** [comment]
If you provide some insights on what you intend to use webgl-operate for, we might be able to provide some pointers for decision making.
